[[exercises]]
name = "intro1"
path = "exercises/00_intro/intro1.rs"
mode = "compile"
hint = """
Remove the `I AM NOT DONE` comment in the `exercises/intro00/intro1.rs` file
to move on to the next exercise."""

[[exercises]]
name = "intro2"
path = "exercises/00_intro/intro2.rs"
mode = "compile"
hint = """
The compiler is informing us that we've got the name of the print macro wrong, and has suggested an alternative."""
